# Generated by Django 5.0.1 on 2024-01-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('EW', 'Electronics'), ('FW', 'Fitness Wear'), ('HD', 'Home Decor'), ('B', 'Books'), ('A', 'Accessories')], max_length=2),
        ),
    ]
